// <auto-generated />
using AddressBook.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AddressBook.Data.Migrations
{
    [DbContext(typeof(ContactsDbContext))]
    partial class ContactsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AddressBook.Core.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Dob")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Dob = "1900-01-01",
                            Email = "superman@dccomics.com",
                            FirstName = "Clark",
                            Surname = "Kent"
                        },
                        new
                        {
                            Id = 2,
                            Dob = "1900-01-01",
                            Email = "batman@dccomics.com",
                            FirstName = "Bruce",
                            Surname = "Wayne"
                        },
                        new
                        {
                            Id = 3,
                            Dob = "1900-01-01",
                            Email = "wonder.woman@dccomics.com",
                            FirstName = "Diana",
                            Surname = "Prince"
                        },
                        new
                        {
                            Id = 4,
                            Dob = "1900-01-01",
                            Email = "ironman@marvel.com",
                            FirstName = "Tony",
                            Surname = "Stark"
                        },
                        new
                        {
                            Id = 5,
                            Dob = "1900-01-01",
                            Email = "spiderman@marvel.com",
                            FirstName = "Peter",
                            Surname = "Parker"
                        },
                        new
                        {
                            Id = 6,
                            Dob = "1900-01-01",
                            Email = "hulk@marvel.com",
                            FirstName = "Bruce",
                            Surname = "Banner"
                        },
                        new
                        {
                            Id = 7,
                            Dob = "1900-01-01",
                            Email = "captain.america@marvel.com",
                            FirstName = "Steve",
                            Surname = "Rogers"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
